//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploiASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrat
    {
        public decimal idContrat { get; set; }
        public System.DateTime dateEntree { get; set; }
        public decimal idTravailleur { get; set; }
        public decimal numero { get; set; }
        public Nullable<System.DateTime> dateSortie { get; set; }
        public string codeAlphabetique { get; set; }
    
        public virtual EntrepriseClient EntrepriseClient { get; set; }
        public virtual ContratTravailleurNonSoumis ContratTravailleurNonSoumis { get; set; }
        public virtual ContratTravailleurSoumis ContratTravailleurSoumis { get; set; }
        public virtual Profession Profession { get; set; }
        public virtual Travailleur Travailleur { get; set; }
    }
}
