//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploiASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntrepriseClient
    {
        public EntrepriseClient()
        {
            this.Contrat = new HashSet<Contrat>();
            this.Interlocuteur = new HashSet<Interlocuteur>();
            this.TraductionEntreprise = new HashSet<TraductionEntreprise>();
        }
    
        public decimal numero { get; set; }
        public string denomination { get; set; }
        public string adresse { get; set; }
        public string numTel { get; set; }
        public decimal nombreTravailleursSoumis { get; set; }
        public decimal nombreTravailleursNonSoumis { get; set; }
    
        public virtual ICollection<Contrat> Contrat { get; set; }
        public virtual ICollection<Interlocuteur> Interlocuteur { get; set; }
        public virtual ICollection<TraductionEntreprise> TraductionEntreprise { get; set; }
    }
}
