//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploiASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interlocuteur
    {
        public decimal idInterlocuteur { get; set; }
        public string Nom { get; set; }
        public decimal numero { get; set; }
    
        public virtual EntrepriseClient EntrepriseClient { get; set; }
    }
}
