//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploiASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Langue
    {
        public Langue()
        {
            this.TraductionProfession = new HashSet<TraductionProfession>();
            this.TraductionEntreprise = new HashSet<TraductionEntreprise>();
        }
    
        public decimal idLangue { get; set; }
        public string libelle { get; set; }
    
        public virtual ICollection<TraductionProfession> TraductionProfession { get; set; }
        public virtual ICollection<TraductionEntreprise> TraductionEntreprise { get; set; }
    }
}
