//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploiASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travailleur
    {
        public Travailleur()
        {
            this.Contrat = new HashSet<Contrat>();
        }
    
        public decimal idTravailleur { get; set; }
        public string nom { get; set; }
        public string adresse { get; set; }
    
        public virtual ICollection<Contrat> Contrat { get; set; }
    }
}
